-- MySQL Script generated by MySQL Workbench
-- Mon Jul 30 13:03:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema youfang_finance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youfang_finance
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_USER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_USER` (
  `ID` VARCHAR(32) NOT NULL,
  `USER_ID` VARCHAR(32) NOT NULL,
  `USER_NAME` VARCHAR(32) NOT NULL,
  `ENCRYPT_PASSWORD` VARCHAR(32) NOT NULL,
  `RANDOM_SALT` VARCHAR(32) NULL,
  `SEX` VARCHAR(1) NULL,
  `MOBILE` VARCHAR(16) NULL,
  `E_MAIL` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `USER_STATUS` VARCHAR(1) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_ROLE` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_ROLE` (
  `ID` VARCHAR(32) NOT NULL,
  `ROLE_NAME` VARCHAR(32) NOT NULL,
  `ROLE_DESC` VARCHAR(256) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `ROLE_STATUS` VARCHAR(1) NULL,
  `SYSTEM_CODE` VARCHAR(10) NULL COMMENT '代表有房子系统的角色设定 DZ: 垫资管理系统',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_FUNCTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_FUNCTION` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_FUNCTION` (
  `ID` VARCHAR(32) NOT NULL,
  `FUN_NAME` VARCHAR(32) NOT NULL,
  `FUN_ICON` VARCHAR(128) NULL,
  `FUN_URL` VARCHAR(128) NOT NULL,
  `PARENT_ID` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `SYSTEM_CODE` VARCHAR(10) NULL COMMENT '代表有房子系统的功能菜单 DZ: 垫资管理系统',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_ROLE_FUN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_ROLE_FUN` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_ROLE_FUN` (
  `ID` VARCHAR(32) NOT NULL,
  `ROLE_ID` VARCHAR(32) NOT NULL,
  `FUN_ID` VARCHAR(32) NOT NULL,
  `CREATE_TIME` VARCHAR(32) NULL,
  `UPDATE_TIME` VARCHAR(32) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_LOG` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_LOG` (
  `ID` VARCHAR(32) NOT NULL,
  `LOG_OPERATOR` VARCHAR(32) NULL,
  `LOG_MODULE` VARCHAR(32) NULL,
  `LOG_DESCRIPTION` VARCHAR(512) NULL COMMENT '日志管理表',
  `LOG_CLASS` VARCHAR(512) NULL,
  `LOG_METHOD` VARCHAR(512) NULL,
  `LOG_PARAMETER` VARCHAR(512) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `LOG_IP` VARCHAR(32) NULL,
  `LOG_ACCOUNT` VARCHAR(32) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_DIANZI_BASE_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_DIANZI_BASE_INFO` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_DIANZI_BASE_INFO` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ENTRY_TIME` DATETIME NULL,
  `MARKET_USERID` VARCHAR(32) NULL COMMENT '市场人员ID',
  `RISK_MANAGE_USERID` VARCHAR(32) NULL COMMENT '风控人员ID',
  `CUSTOMER_CHANNEL` VARCHAR(10) NULL COMMENT '客户来源渠道',
  `BUYER_NAME` VARCHAR(128) NULL COMMENT '买方姓名 多个用逗号分隔',
  `SELLER_NAME` VARCHAR(128) NULL COMMENT '卖方姓名',
  `BORROWER` VARCHAR(128) NULL,
  `TOTAL_MONEY` DECIMAL(10,2) NULL,
  `REDEEM_MONEY` DECIMAL(10,2) NULL,
  `TRANSFER_MONEY` DECIMAL(10,2) NULL,
  `MONEY_CHANNEL` VARCHAR(10) NULL,
  `BELONG_EXCHAGE` VARCHAR(10) NULL,
  `HOUSE_ADDR` VARCHAR(512) NULL,
  `PLEDGE_REG` VARCHAR(1) NULL COMMENT '是否质押登记',
  `BUYER_MOBILE` VARCHAR(12) NULL,
  `BUYER_IDCARD` VARCHAR(32) NULL,
  `SELLER_MOBILE` VARCHAR(12) NULL,
  `SELLER_IDCARD` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_ELEC_FILES_SELLER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_ELEC_FILES_SELLER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_ELEC_FILES_SELLER` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `FILE_URI` VARCHAR(128) NULL COMMENT 'ex: /seller/案件id/xxxx.png',
  `FILE_CATEGORY` VARCHAR(4) NULL COMMENT '1:身份证 2:户口本 3: 婚姻证明（结婚证，离婚证）4:征信报告 5: 借款合同、抵押合同  6:房产证 (复印件) 7:产调报告 8:还款明细 9: 公证书 10:审批截图 11: 其他',
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_ELEC_FILES_SELLER_YF_DIANZI_BASE_INFO_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_ELEC_FILES_SELLER_YF_DIANZI_BASE_INFO`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_DIC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_DIC` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_DIC` (
  `ID` INT NOT NULL,
  `DISPLAY_NAME` VARCHAR(64) NOT NULL,
  `VALUE` VARCHAR(10) NOT NULL,
  `PRIORITY` INT NULL,
  `PARENTID` VARCHAR(10) NULL,
  `REMARK` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_NOTARIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_NOTARIZATION` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_NOTARIZATION` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL,
  `NOTARIA` VARCHAR(10) NULL,
  `NOTARY` VARCHAR(45) NULL,
  `CLIENT` VARCHAR(45) NULL,
  `TRUSTEE` VARCHAR(45) NULL,
  `AGENT_ID` VARCHAR(32) NULL,
  `AMOUNT` INT NULL,
  `HANDLE_TIME` DATETIME NULL,
  `DOC_BACK_TIME` DATETIME NULL,
  `DOC_TYPE` VARCHAR(1) NULL COMMENT 'S: SELLER B: BUYER',
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_NOTARIZATION_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_NOTARIZATION_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_ELEC_FILES_BUYER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_ELEC_FILES_BUYER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_ELEC_FILES_BUYER` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '初次上传的时候产生一个案件ID用来关联流程',
  `FILE_URI` VARCHAR(128) NULL COMMENT 'ex: /seller/案件id/xxxx.png',
  `FILE_CATEGORY` VARCHAR(4) NULL COMMENT '1:身份证 2:户口本 3: 婚姻证明（结婚证，离婚证）4:征信报告 5: 借款合同、抵押合同  6:房产证 (复印件) 7:产调报告 8:还款明细 9: 公证书 10:审批截图 11: 其他',
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_ELEC_FILES_BUYER_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_ELEC_FILES_BUYER_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_ELEC_FILES_AGENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_ELEC_FILES_AGENT` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_ELEC_FILES_AGENT` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `FILE_URI` VARCHAR(128) NULL COMMENT 'ex: /seller/案件id/xxxx.png',
  `FILE_CATEGORY` VARCHAR(4) NULL COMMENT '1:身份证 2:户口本 3: 婚姻证明（结婚证，离婚证）4:征信报告 5: 借款合同、抵押合同  6:房产证 (复印件) 7:产调报告 8:还款明细 9: 公证书 10:审批截图 11: 其他 12:风控报告',
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_ELEC_FILES_AGENT_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_ELEC_FILES_AGENT_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_MORTGAGE_BUYER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_MORTGAGE_BUYER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_MORTGAGE_BUYER` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `MORTGAGE_BANK` VARCHAR(128) NULL,
  `LOAN_AMOUNT` DECIMAL(10,2) NULL,
  `BRORROWER` VARCHAR(45) NULL,
  `RECEIVER` VARCHAR(45) NULL,
  `APPROVE_TIME` DATETIME NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_MORTGAGE_BUYER_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_MORTGAGE_BUYER_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_CHECK_REPAY_SELLER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_CHECK_REPAY_SELLER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_CHECK_REPAY_SELLER` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `BANK_NAME` VARCHAR(128) NULL,
  `DEBT_AMOUNT` DECIMAL(10,2) NULL,
  `EXPECT_REDEEM_TIME` DATETIME NULL,
  `ACTUAL_PAY_AMOUNT` DECIMAL(10,2) NULL,
  `REPAY_TIME` DATETIME NULL,
  `EXPCET_TAKE_TIME` DATETIME NULL,
  `TAKE_TIME` DATETIME NULL,
  `AGENY_ID` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_CHECK_REPAY_SELLER_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_CHECK_REPAY_SELLER_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_CANCELL_TRANSFER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_CANCELL_TRANSFER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_CANCELL_TRANSFER` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `RELEASE_TIME` DATETIME NULL,
  `CANCELL_TAKE_TIME` DATETIME NULL,
  `TRANSFER_APPOINTMENT_TIME` DATETIME NULL,
  `EXPECT_TAKE_TIME` DATETIME NULL,
  `TRANSFER_TAKE_TIME` DATETIME NULL,
  `REPAY_TIME` DATETIME NULL,
  `TAKE_AGENT_ID` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_CANCELL_TRANSFER_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_CANCELL_TRANSFER_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_REMORTGAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_REMORTGAGE` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_REMORTGAGE` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `APPOINTMENT_TIME` DATETIME NULL,
  `HANDLE_TIME` DATETIME NULL,
  `TAKE_TIME` DATETIME NULL,
  `TAKE_AGENT_ID` VARCHAR(32) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_REMORTGAGE_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_REMORTGAGE_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_RETURN_LOAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_RETURN_LOAN` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_RETURN_LOAN` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `RETURN_TIME` DATETIME NULL,
  `EXCEPT_LOAN_TIME` DATETIME NULL,
  `ACTUAL_LOAN_TIME` DATETIME NULL,
  `LOAN_AMOUNT` DECIMAL(10,2) NULL,
  `ACTUAL_PAY_AMOUNT` DECIMAL(10,2) NULL,
  `PENALTY_AMOUNT` DECIMAL(10,2) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_RETURN_LOAN_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_RETURN_LOAN_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_SERVICE_FEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_SERVICE_FEE` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_SERVICE_FEE` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `EXPECT_CHARGE_AMOUNT` DECIMAL(10,2) NULL,
  `ACTUAL_CHARGE_AMOUNT` DECIMAL(10,2) NULL,
  `LEAVE_CHARGE_AMOUNT` DECIMAL(10,2) NULL,
  `CHARGE_MONTHLY` VARCHAR(1) NULL,
  `CHANNEL_COMMISSION` DECIMAL(10,2) NULL,
  `REDEEM_TAKE_MONEY_DAYS` INT NULL,
  `TRANSFER_TAKE_MONEY_DAYS` INT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_SERVICE_FEE_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_SERVICE_FEE_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_CUSTODY_FEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_CUSTODY_FEE` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_CUSTODY_FEE` (
  `ID` VARCHAR(32) NOT NULL,
  `CASE_ID` VARCHAR(32) NULL COMMENT '案件ID用来关联流程',
  `TOTAL_AMOUNT` DECIMAL(10,2) NULL,
  `FIRST_PAY_AMOUNT` DECIMAL(10,2) NULL,
  `LEAVE_CHARGE_AMOUNT` DECIMAL(10,2) NULL,
  `TAX_AMOUNT` DECIMAL(10,2) NULL,
  `ACTUAL_TAX_AMOUNT` DECIMAL(10,2) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_YF_CUSTODY_FEE_YF_DIANZI_BASE_INFO1_idx` (`CASE_ID` ASC),
  CONSTRAINT `fk_YF_CUSTODY_FEE_YF_DIANZI_BASE_INFO1`
    FOREIGN KEY (`CASE_ID`)
    REFERENCES `youfang_finance`.`YF_DIANZI_BASE_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youfang_finance`.`YF_ROLE_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youfang_finance`.`YF_ROLE_USER` ;

CREATE TABLE IF NOT EXISTS `youfang_finance`.`YF_ROLE_USER` (
  `ID` VARCHAR(32) NOT NULL,
  `ROLE_ID` VARCHAR(32) NOT NULL,
  `USER_PK_ID` VARCHAR(32) NOT NULL,
  `CREATE_TIME` VARCHAR(32) NULL,
  `UPDATE_TIME` VARCHAR(32) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

